const fs = require('fs');
const path = require('path');
const translate = require('google-translate-api-x');

// Dictionaries for standard fields
const MUSCLE_MAP = {
  abdominals: 'Abdominales', abductors: 'Abductores', adductors: 'Aductores',
  biceps: 'Bíceps', calves: 'Pantorrillas', chest: 'Pecho', forearms: 'Antebrazos',
  glutes: 'Glúteos', hamstrings: 'Isquiotibiales', lats: 'Dorsales',
  'lower back': 'Espalda Baja', 'middle back': 'Espalda Media', neck: 'Cuello',
  quadriceps: 'Cuádriceps', shoulders: 'Hombros', traps: 'Trapecios', triceps: 'Tríceps'
};

const CATEGORY_MAP = {
  strength: 'Fuerza', stretching: 'Estiramiento', plyometrics: 'Pliometría',
  strongman: 'Strongman', powerlifting: 'Powerlifting', cardio: 'Cardio',
  'olympic weightlifting': 'Halterofilia'
};

const EQUIPMENT_MAP = {
  'body only': 'Peso Corporal', 'machine': 'Máquina', 'other': 'Otro',
  'foam roll': 'Foam Roller', 'kettlebells': 'Kettlebells', 'dumbbell': 'Mancuernas',
  'cable': 'Polea', 'barbell': 'Barra', 'bands': 'Bandas',
  'medicine ball': 'Balón Medicinal', 'exercise ball': 'Balón Suizo', 'e-z curl bar': 'Barra EZ'
};

function delay(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }

async function run() {
  console.log('Reading local exercises.json...');
  const raw = fs.readFileSync(path.join(__dirname, 'exercises.json'), 'utf8');
  const data = JSON.parse(raw);
  
  let sql = `-- Seed generated by AI via Google Translate API\n`;
  sql += `INSERT INTO public.exercises (id, name_en, name_es, muscle, equipment, category, instructions_en, instructions_es) VALUES\n`;
  
  const values = [];
  const BATCH_SIZE = 50;
  
  const limit = data.length;
  console.log(`Processing ${limit} exercises in batches...`);

  for (let i = 0; i < limit; i += BATCH_SIZE) {
    const batch = data.slice(i, i + BATCH_SIZE);
    console.log(`Translating batch ${i} to ${i + batch.length}...`);
    
    const namesToTranslate = batch.map(e => e.name);
    // Let's only translate names to save time. Instructions can be English, or translated later.
    // We'll translate both just to try.
    const instsToTranslate = batch.map(e => (e.instructions || []).join(' '));
    
    try {
      const namesRes = await translate(namesToTranslate, { to: 'es' });
      // Only do names for speed and reliability, skip instructions for now if it fails
      
      for (let j = 0; j < batch.length; j++) {
        const item = batch[j];
        const name_en = item.name.replace(/'/g, "''");
        
        let name_es = name_en;
        if (namesRes[j] && namesRes[j].text) {
          name_es = namesRes[j].text.replace(/'/g, "''");
        }
        
        const inst_en = instsToTranslate[j].replace(/'/g, "''");
        const inst_es = inst_en; // Skipped instruction translation to avoid huge API payloads
        
        const muscle = MUSCLE_MAP[item.primaryMuscles?.[0]] || item.primaryMuscles?.[0] || 'Otro';
        const category = CATEGORY_MAP[item.category] || item.category || 'Otro';
        const equipment = EQUIPMENT_MAP[item.equipment] || item.equipment || 'Otro';
        
        values.push(`(gen_random_uuid(), '${name_en}', '${name_es}', '${muscle}', '${equipment}', '${category}', '${inst_en}', '${inst_es}')`);
      }
      
      await delay(1000);
    } catch (err) {
      console.error('Translation error in batch:', err.message);
      break;
    }
  }
  
  sql += values.join(',\n') + ';\n';
  
  const outputPath = path.join(__dirname, '..', '..', '..', 'supabase', 'migrations', '20260910170000_seed_exercises.sql');
  fs.writeFileSync(outputPath, sql);
  console.log(`Generated migration at ${outputPath}`);
}

run();
